#See https://aka.ms/containerfastmode to understand how Visual Studio uses this Dockerfile to build your images for faster debugging.

FROM mcr.microsoft.com/dotnet/aspnet:5.0-buster-slim AS base
WORKDIR /app
EXPOSE 80
EXPOSE 443

FROM mcr.microsoft.com/dotnet/sdk:5.0-buster-slim AS build
WORKDIR /src
COPY ["StellarGlobeShop.Gateway.Service/StellarGlobeShop.Gateway.Service.csproj", "StellarGlobeShop.Gateway.Service/"]
RUN dotnet restore "StellarGlobeShop.Gateway.Service/StellarGlobeShop.Gateway.Service.csproj"
COPY . .
WORKDIR "/src/StellarGlobeShop.Gateway.Service"
RUN dotnet build "StellarGlobeShop.Gateway.Service.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "StellarGlobe.MyShop.Service.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .
ENTRYPOINT ["dotnet", "StellarGlobe.MyShop.Service.dll"]